# Generated by Django 2.0.3 on 2019-11-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20191121_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subType', models.CharField(choices=[('Cheese', 'Cheese'), ('Italian', 'Italian'), ('Ham & Cheese', 'Ham & Cheese'), ('Meatball', 'Meatball'), ('Tuna', 'Tuna'), ('Turkey', 'Turkey'), ('Chicken Parmigiana', 'Chicken Parmigiana'), ('Eggplant Parmigiana', 'Eggplant Parmigiana'), ('Steak', 'Steak'), ('Steak & Cheese', 'Steak & Cheese'), ('Sausage, Peppers & Onions', 'Sausage, Peppers & Onions'), ('Hamburger', 'Hamburger'), ('Cheeseburger', 'Cheeseburger'), ('Fried Chicken', 'Fried Chicken'), ('Veggie', 'Veggie')], max_length=25)),
                ('size', models.CharField(choices=[('Small', 'Small'), ('Large', 'Large')], max_length=5)),
                ('mushroomsAvail', models.BooleanField(default=False)),
                ('pepppersAvail', models.BooleanField(default=False)),
                ('onionsAvail', models.BooleanField(default=False)),
                ('extrasPrice', models.DecimalField(decimal_places=2, max_digits=2)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
