# Generated by Django 2.0.3 on 2019-11-28 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_subs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subs',
            old_name='pepppersAvail',
            new_name='peppersAvail',
        ),
    ]
