# Generated by Django 2.0.3 on 2019-11-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20191128_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='subs',
            name='smallAvail',
            field=models.BooleanField(default=True),
        ),
    ]
