# Generated by Django 2.0.3 on 2019-11-29 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_pasta_salads'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasta',
            name='dinnerAvail',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pasta',
            name='size',
            field=models.CharField(choices=[('Reg', 'Reg'), ('Small', 'Small'), ('Large', 'Large')], default='Reg', max_length=5),
        ),
        migrations.AddField(
            model_name='salads',
            name='dinnerAvail',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='salads',
            name='size',
            field=models.CharField(choices=[('Reg', 'Reg'), ('Small', 'Small'), ('Large', 'Large')], default='Reg', max_length=5),
        ),
    ]
