# Generated by Django 2.0.3 on 2019-12-12 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20191206_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('itemId', models.IntegerField()),
                ('orderId', models.IntegerField(default=0)),
                ('itemChoice', models.IntegerField(choices=[(0, 'PizzaTopping'), (1, 'RegularPizza'), (2, 'SicilianPizza'), (3, 'SubTopping'), (4, 'Subs'), (5, 'Pasta'), (6, 'Salads'), (7, 'DinnerPasta'), (8, 'DinnerSalad')], default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('status', models.IntegerField(choices=[(0, 'Cancelled'), (1, 'Cart'), (2, 'Submitted'), (3, 'In Progress'), (4, 'Assembling'), (5, 'Cooking'), (6, 'Packaging'), (7, 'Completed')], default=0)),
                ('itemDesc', models.CharField(default=None, max_length=100)),
                ('specialInstructions', models.CharField(default=None, max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='subs',
            name='addMushrooms',
        ),
        migrations.RemoveField(
            model_name='subs',
            name='addOnions',
        ),
        migrations.RemoveField(
            model_name='subs',
            name='addPeppers',
        ),
        migrations.AddField(
            model_name='subtopping',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='numToppings',
            field=models.IntegerField(choices=[(0, 'Cheese'), (1, '1 Item'), (2, '2 Items'), (3, '3 Items'), (4, 'Special')], default=0),
        ),
    ]
