# Generated by Django 2.0.3 on 2019-12-12 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20191212_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodorder',
            name='status',
            field=models.IntegerField(choices=[(0, 'Cancelled'), (1, 'Cart'), (2, 'Submitted'), (3, 'In Progress'), (4, 'Assembling'), (5, 'Cooking'), (6, 'Packaging'), (7, 'Completed')], default=1),
        ),
    ]
