# Generated by Django 2.0.3 on 2019-12-12 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20191212_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodorder',
            name='specialInstructions',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
